### ISSUE TITLE
Traduzir livro sabedoria do elefante do cal evans

### ISSUE THREAD

**Issue by reginaldojunior** [backend-br/traduzindo#1]
O livro sabedoria do elefante (Wisdom of the elephant) é um livro escrito em inglês pelo Cal Evans e tenho autorização para traduzir-lo com a comunidade, conversei com o próprio cal através do twitter e e-mail.

O projeto de tradução está neste repositório.

https://github.com/reginaldojunior/wisdom-of-the-elephant

**Comment by RogerioVM** [comment]
Olá, Reginaldo!
Vi que este projeto já tem algum tempo, porém gostaria de saber como está o andamento dele, pois tenho interesse em contribuir.Tenho ótimo conhecimento da língua inglesa e sou meio que iniciante com Github, por isso quero ser mais ativo por aqui.

Abraço.

**Comment by reginaldojunior** [comment]
Olá, 

O Projeto está sim, mas infelizmente eu perdi o meu exemplar físico e não consigo mais escrever as paginas inglês para passamos posteriormente para português, preciso verificar se alguém tem um exemplar ou se tem uma versão digital do livro.

**Comment by RogerioVM** [comment]
Ah sim entendo. Tudo bem, qualquer coisa se vc tiver algum projeto parecido, ou até mesmo saber de algum e tal, eu estou disponível cara. Não só pra traduções mas pra qualquer outra coisa que eu possa fazer.

Abraço
